name: Main Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v2.0.1
        with:
          image_version: latest
          port: 27017
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: .m2/repository # maven repository files are stored here
          key: ${{ runner.OS }}-maven-${{ hashFiles('pom.xml') }}
      - name: Build
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v4
        # Test run screenshots only on failure
        if: success()
        with:
          name: quarkus-mongo.jar
          path: quarkus-mongo/target/quarkus-mongo.jar
      - uses: actions/upload-artifact@v4
        # Test run screenshots only on failure
        if: success()
        with:
          name: quarkus-mongo-test.jar
          path: quarkus-mongo-test/target/quarkus-mongo-test.jar
